
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =            2391
     no. of nonzeroes in lower triangle of a =          124185
     no. of nonzeroes in the factor l        =          312852
     ratio of nonzeroes in factor (min/max)  =          0.7420
     number of super nodes                   =              67
     maximum order of a front matrix         =             258
     maximum size of a front matrix          =           33411
     maximum size of a front trapezoid       =           29040
     METIS reordering method used 
     no. of floating point ops for factor    =      3.6381D+07
     no. of floating point ops for solve     =      1.0835D+06
     ratio of flops for factor (min/max)     =          0.6647
     ratio of allocated memory (max/min)     =          1.1465
     number of positive pivots               =            2391
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000238
     time (cpu & wall) for ordering          =        0.000000        0.001629
     time (cpu & wall) for other matrix prep =        0.000000        0.001035
     time (cpu & wall) for value input       =        0.000000        0.000680
     time (cpu & wall) for matrix distrib.   =        0.000000        0.005472
     time (cpu & wall) for numeric factor    =        0.015625        0.007047
     computational rate (gflops) for factor  =        2.328409        5.163044

     no input or output performed

  Solver Memory allocated on core    0       =        2.182 MB
  Solver Memory allocated on core    1       =        1.989 MB
  Solver Memory allocated on core    2       =        2.150 MB
  Solver Memory allocated on core    3       =        1.903 MB
  Total Solver Memory allocated by all cores =        8.224 MB

