
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           81312
     no. of nonzeroes in lower triangle of a =         1294584
     no. of nonzeroes in the factor l        =         9719706
     ratio of nonzeroes in factor (min/max)  =          0.8171
     number of super nodes                   =            4222
     maximum order of a front matrix         =             590
     maximum size of a front matrix          =          174345
     maximum size of a front trapezoid       =          135200
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      1.5298D+09
     no. of floating point ops for solve     =      3.4480D+07
     ratio of flops for factor (min/max)     =          0.8113
     ratio of allocated memory (max/min)     =          1.1675
     number of positive pivots               =           81312
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.001537
     time (cpu & wall) for ordering          =        0.062500        0.068819
     time (cpu & wall) for other matrix prep =        0.015625        0.011191
     time (cpu & wall) for value input       =        0.000000        0.002091
     time (cpu & wall) for matrix distrib.   =        0.015625        0.020044
     time (cpu & wall) for numeric factor    =        0.031250        0.037183
     computational rate (gflops) for factor  =       48.953221       41.142471
     time (cpu & wall) for numeric solve     =        0.015625        0.006068
     computational rate (gflops) for solve   =        2.206697        5.681929
     effective I/O rate (GB/sec) for solve   =        8.221241       21.168514

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        229376.        2. MB        227291.        2. MB
                95-   1        229376.        2. MB        222485.        2. MB
                95-   2        294912.        2. MB        267964.        2. MB
                95-   3        294912.        2. MB        267284.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:       1048576.        8. MB        985024.        8. MB


  Solver Memory allocated on core    0       =       37.117 MB
  Solver Memory allocated on core    1       =       36.127 MB
  Solver Memory allocated on core    2       =       42.176 MB
  Solver Memory allocated on core    3       =       42.105 MB
  Total Solver Memory allocated by all cores =      157.525 MB

